### ISSUE TITLE
hangs on sample data - linux

### ISSUE THREAD

**Issue by colindaven** [BSGOxford/BrowseVCF#1]
Hi.

Unfortunately browseVCF hangs on selection of the sample file on Linux Ubuntu 16.04. This happens with a VCF or VCF.gz file.

Any ideas ?
Colin

davenpor@galaxy1:/var/www/programs/web$ ./launcher-gnu.sh 
/var/www/programs/web/../python27gnu/bin:/home/davenpor/bin:/home/davenpor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
Python 2.7.11
ARGS: ['launcher-cherrypy.py', '/var/www/programs/web/../python27gnu/bin/python']
PROCS: None
[19/Jan/2017:14:32:51] ENGINE Bus STARTING
[19/Jan/2017:14:32:51] ENGINE Started monitor thread 'Autoreloader'.
[19/Jan/2017:14:32:51] ENGINE Serving on http://127.0.0.1:59279
[19/Jan/2017:14:32:51] ENGINE Bus STARTED
Chosen /home/davenpor/programs/browseVCF/sample_file.vcf

**Comment by silvia-s** [comment]
Hi Colin,

Perhaps Varun would be the best person to reply to your question, as he developed the frontend part of the tool... In the meantime, could you just tell me which is your default browser? And could you tell me what happens when you run the following command?

`python -m webbrowser -t "http://www.python.org"`

If the command above doesn't open any browser, you could try setting `BROWSER=firefox` (or whatever) and re-launching BrowseVCF. 

Is there something else after "Chosen ..."? Normally, after choosing the vcf/vcf.gz file, you should see on the terminal a set of requests (_e.g.: 127.0.0.1 - - [19/Jan/2017:14:02:33] "GET / HTTP/1.1" 200 1846 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"_) and your default browser should open a new tab to let you filter your file interactively from there.

Alternatively, you could use the command-line version of BrowseVCF by simply running the individual scripts in BrowseVCF_gnu_X.X/web/scripts/

Cheers,
Silvia

**Comment by colindaven** [comment]
Hi Silvia,

thanks for your help. I didn't realize it needed a GUI on the local machine, I had installed it on a web server since I am hoping to serve VCFs interactively for (non-command line interested) collaborators at my institution.

I will reinstall on a app server with a local (on machine) GUI and webbrowser and see if I get any further.

Thanks,
Colin

**Comment by colindaven** [comment]
Hello again,

so I got quite a bit further on local workstation.

`~/programs/browsevcf/web$ ./launcher-gnu.sh 
/home/colin/programs/browsevcf/web/../python27gnu/bin:/home/colin/bin:/home/colin/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Python 2.7.11
ARGS: ['launcher-cherrypy.py', '/home/colin/programs/browsevcf/web/../python27gnu/bin/python']
PROCS: None
[24/Jan/2017:14:56:57] ENGINE Bus STARTING
[24/Jan/2017:14:56:57] ENGINE Started monitor thread 'Autoreloader'.
[24/Jan/2017:14:56:57] ENGINE Serving on http://127.0.0.1:48799
[24/Jan/2017:14:56:57] ENGINE Bus STARTED
Chosen /home/colin/2017/rat/x.hard-filtered.vcf`

However, local firefox on the same PC is giving me a "Unable to connect
Firefox can’t establish a connection to the server at 127.0.0.1:48799."

I checked the firefox no_proxy settings, and 127.0.0.1 is set as no proxy. 

I also tried localhost:48799 and from my own PC <ip_address>:48799. All gave the same result as above. 

Is there a test VCF posted somewhere or do you have any more ideas ? Where is the webserver log being stored for example ?

Thanks,
Colin

**Comment by silvia-s** [comment]
Hi Colin,

Yes, there's a test VCF file (named "sample_file.vcf.gz"), which you can download from the [release page](https://github.com/BSGOxford/BrowseVCF/releases) of this repository. The log is not stored anywhere, all messages are sent to the stdout.

BrowseVCF is meant to be used locally on a PC and consists of a web server that runs - _locally_ - without need of internet connection (you can find more details about this in our [publication](http://bib.oxfordjournals.org/content/early/2016/08/04/bib.bbw054)). Therefore, if your "non-command line interested" collaborators want to use it, they could simply download the .zip or .tar.gz bundle for their operating system, extract it and follow the instructions on GitHub to launch BrowseVCF using the GUI on _locally-stored_ VCF files.

However, if you think there might be a way to make it also work remotely as you'd like, feel free to fork our repository and change it according to your needs.

Cheers,
Silvia
