### ISSUE TITLE
Error at script01_preprocess.py

### ISSUE THREAD

**Issue by kkapuria3** [BSGOxford/BrowseVCF#5]
Hello,
I am using an in-house annotated vcf file. While using the web GUI, I get the same formatting errors mentioned in other posts. Hence, I am trying to run the script01_preprocess.py so as to know where its breaking. 

`python2 script01_preprocess.py -i ../../../gvanno-1.3.2/examples/M-WES011-I6227-grch37.vcf.gz -o ~/gvanno-1.3.2/examples/`

At this point I am clueless how to debug this.

```
Traceback (most recent call last):
  File "script01_preprocess.py", line 315, in <module>
    main()
  File "script01_preprocess.py", line 312, in main
    script01_api_call(args.inp_file, args.out_folder)
  File "script01_preprocess.py", line 296, in script01_api_call
    out_folder)
  File "script01_preprocess.py", line 212, in parse_inp_file
    line = split_vep_field(sub_fields, line, vep_symbol)
  File "script01_preprocess.py", line 141, in split_vep_field
    all_values[x].append(vep[x])
IndexError: list index out of range
```

**Comment by silvia-s** [comment]
It sounds as the problem might be related to the VEP annotation of your file. Have you checked that it's in line with the VCF specifications (https://samtools.github.io/hts-specs/VCFv4.3.pdf)? It might also be a good idea to validate your VCF file (for example, using https://github.com/EBIvariation/vcf-validator or https://vcftools.github.io/perl_module.html#vcf-validator) to look for any formatting errors before loading it into BrowseVCF.

This software is no longer supported since July 2020 (see latest update in the README.md file) so I can't help you much, I'm afraid :-/

**Comment by kkapuria3** [comment]
Thanks much. I checked my files with (https://vcftools.github.io/perl_module.html#vcf-validator) and there seems to be no formatting specific error. I will rerun my VEP annotations using SnpEff and try doing the same. I think there is an ambiguity in one of the headers which breaks the list index. Would you know a easy way to find/print line number in vcf file where code breaks ?

**Comment by silvia-s** [comment]
You could write a `print line` at line 186 (i.e. just after `for line in inp:`) of the file "script01_preprocess.py", so that the last printed line on the stdout would be the troublesome one. 

Hope this helps!

**Comment by kkapuria3** [comment]
Helps a lot. Thanks.
